class BotData {
  static const username = [
    "Thura",
    "John",
    "Michael",
    "David",
    "James",
    "Robert",
    "William",
    "Daniel",
    "Joseph",
    "Matthew",
    "Andrew",
    "Christopher",
    "Joshua",
    "Ryan",
    "Anthony",
    "Thomas",
    "Phyo Wai",
    "Kevin",
    "Jason",
    "Brandon",
    "Justin",
    "Zaw Zaw",
    "Tyler",
    "Jack",
    "Oliver",
    "Harry",
    "Shine Khant",
    "George",
    "Charlie",
    "Noah",
    "Leo",
    "Oscar",
    "Arthur",
    "Freddie",
    "Pierre",
    "Louis",
    "Jean",
    "Antoine",
    "Lucas",
    "Hugo",
    "Jules",
    "Nicolas",
    "Alexandre",
    "Myo Min",
    "Theo",
    "Hans",
    "Lukas",
    "Felix",
    "Max",
    "Leon",
    "Jonas",
    "Tim",
    "Paul",
    "Finn",
    "Ben",
    "Carlos",
    "Kyaw Gyi",
    "Miguel",
    "Jose",
    "Juan",
    "Diego",
    "Luis",
    "Javier",
    "Pablo",
    "Antonio",
    "Alejandro",
    "Marco",
    "Luca",
    "Giovanni",
    "Matteo",
    "Francesco",
    "Ko Ko",
    "Alessandro",
    "Riccardo",
    "Andrea",
    "Stefano",
    "Davide",
    "Ivan",
    "Dmitry",
    "Sergey",
    "Alexei",
    "Nikolai",
    "Thiha",
    "Vladimir",
    "Mikhail",
    "Andrei",
    "Yuri",
    "Pavel",
    "Wei",
    "Jun",
    "Ming",
    "Jian",
    "Nyein Chan",
    "Lei",
    "Hao",
    "Peng",
    "Tao",
    "Bin",
    "Qiang",
    "Haruto",
    "Yuki",
    "Ren",
    "Sota",
    "Kaito",
    "Takumi",
    "Daichi",
    "Riku",
    "Yuma",
    "Kenta",
    "Min Jun",
    "Seo Jun",
    "Moe Yan",
    "Ji Hoon",
    "Hyun Woo",
    "Joon Ho",
    "Sung Min",
    "Dong Hyun",
    "Thet Naing",
    "Jae Woo",
    "Woo Jin",
    "Tae Hyun",
    "Ananda",
    "Htet Aung",
    "Somchai",
    "Niran",
    "Chaiya",
    "Prasert",
    "Sakda",
    "Narong",
    "Kiet",
    "Wichai",
    "Arthit",
    "Nguyen",
    "Minh",
    "Lin Htet",
    "Bao",
    "Duc",
    "Huy",
    "Quang",
    "Sai Sai",
    "Tuan",
    "Nam",
    "Phong",
    "Khanh",
    "Arjun",
    "Rahul",
    "Vikram",
    "Amit",
    "Rohan",
    "Karan",
    "Raj",
    "Aditya",
    "Sanjay",
    "Manish",
    "Ahmed",
    "Mohammed",
    "Omar",
    "Ali",
    "Hassan",
    "Yousef",
    "Khalid",
    "Faisal",
    "Tariq",
    "Min Thu",
    "Abdullah",
    "Mehmet",
    "Emre",
    "Can",
    "Ahmet",
    "Mustafa",
    "Burak",
    "Kerem",
    "Mert",
    "Onur",
    "Yusuf",
    "Joao",
    "Pedro",
    "Gabriel",
    "Lucas",
    "Mateus",
    "Kaung Myat",
    "Rafael",
    "Bruno",
    "Felipe",
    "Gustavo",
    "Thiago",
    "Soe Moe",
    "Sipho",
    "Thabo",
    "Mandla",
    "Bongani",
    "Sibusiso",
    "Nkosinathi",
    "Themba",
    "Musa",
    "Lwazi",
    "Ye Yint",
    "Andile",
    "Noah",
    "Liam",
    "Ethan",
    "Mason",
    "Logan",
    "Aiden",
    "Jacob",
    "Samuel",
    "Nathan",
    "Nanda",
    "Caleb",
    "PlayerOne",
    "Legend",
    "Champion",
    "King",
    "Warrior",
    "Aung Aung",
    "Sniper",
    "Dragon",
    "Phoenix",
    "Falcon",
    "Wolf",
  ];

  static const avatars = [
    "/YC1wGFc1/default.png",
    "/zDnJPsL4/Free-cat.png",
    "/3rgKbsyV/Free-dog.png",
    "/gcvYBCwT/Free-chicken.png",
    "/gcvYBCwB/Free-cow.png",
    "/qB8kZPhH/Free-monkey.png",
    "/W4F7MSpr/Moshie-Contract-Killer.png",
    "/xTdMjD1y/Lion-King.png",
  ];

  static const borders = [
    "/bvQWHJh9/border_1.png",
    "/T1nBNvCJ/Flim-border.png",
    "/tJF8vG22/Vine-border.png",
    "/rs57Z2Q9/golden-crown-border.png",
    "/PJnH3kFT/premium.png",
    "/8CvrB1B7/cherry.png",
    "/g0h6qYqw/Stone.png",
    "/zvg2f6Wt/Water-border.png",
    "/XqC1vmF2/Egypt-border.png",
  ];

  static const banners = [
    "/VLjhbdVR/banner-1.png",
    "/Yq1PmhPK/banner-2.png",
    "/VLjhbdhm/banner-3.png",
    "/Gps5W1tC/banner-4.png",
    "/DzwRN1zx/banner_5.png",
    "/8CHRsgzy/banner_6.png",
    "/8kYPvqbM/banner-7.png",
  ];
}
